### ISSUE TITLE
Rename and Trash Icons stay after hover

### ISSUE THREAD

**Issue by chinm4** [vizhub-core/vzcode#505] opened 2024-02-05 02:22 UTC
When navigating up on the sidebar over the Rename and Trash icons the icons are staying there permanently until hovered again
![afterhoveringuponeachfilesicons](https://github.com/vizhub-core/vzcode/assets/90073238/42df2d7f-f862-4c4f-b0e3-fb5fb0e0f3f5)

**Comment by curran** [comment] 2024-02-05 16:26
Are you on the latest `main`?

**Comment by curran** [comment] 2024-02-05 16:26
Interesting... I cannot reproduce it.

**Comment by curran** [comment] 2024-02-05 16:32
If we change the hover display for those buttons to be done with CSS rather than JS, I think that would solve this issue.

Otherwise, we may need to listen for more types of mouse events. Maybe it's not getting the mouse out, or there may be some issue with event bubbling out of the tooltip.

**Comment by curran** [comment] 2024-02-06 13:08
Possibly related to these new changes

https://github.com/vizhub-core/vzcode/pull/493

**Comment by curran** [comment] 2024-02-16 17:15
Another idea on this: the problem seems to be caused by mouse events on the tooltip. What if we just disable all pointer events for the tooltip? That could be an easy fix.

**Comment by curran** [comment] 2024-02-27 16:17
Here's an idea for a fix: move the state of the hovered item up one level in the component tree.

Or maybe we could just use CSS to show/hide the icons when you hover on the parent.

**Comment by curran** [comment] 2024-03-26 10:04
Finally fixed in https://github.com/vizhub-core/vzcode/pull/617 !

**Closed** 2024-03-26 10:05 UTC
