### ISSUE TITLE
Download image shows .json file

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vzcode#685] opened 2024-05-18 16:41 UTC
![image](https://github.com/vizhub-core/vzcode/assets/13540669/1ca25039-1b8e-4db6-bf28-e7fc8047683e)

**Comment by curran** [comment] 2024-05-22 15:02
I just tested the image download on a public viz and it works fine for me. In your screenshot it looks like you have no disk space left, so maybe all you see in the list is previous downloads?

Closing this issue for now, but if you can provide a way for me to reproduce the issue I can look into it.

**Closed by curran** 2024-05-22 15:02 UTC
